### ISSUE TITLE
FEATURE: Add CC Recipients in EmailService

### ISSUE THREAD

**Issue by paavo** [code-q-web-factory/CodeQ.LinkChecker#22]
It would be nice to add CC Recipients to an E-Mail.
This would be nice to add a Client to a Support-Ticket (Jira Service Desk) for example. 

emailto: support@company.tld
cc: client@clientdomain.tld

**Comment by rolandschuetz** [comment]
Hello @paavo ,

sure, feel free to make a PR, we'll review and merge it.

**Comment by rolandschuetz** [comment]
See https://github.com/code-q-web-factory/CodeQ.LinkChecker/blob/main/Classes/Infrastructure/EmailService.php#L92

**Comment by rolandschuetz** [comment]
@paavo I'm fully reworking the package, releasing it in the next few days.

This is now implemented in `EmailService`.

You can now configure CC recipients via:

```yaml
NEOSidekick:
  LinkChecker:
    notifications:
      mail:
        ccRecipient:
          default:
            name: 'Client'
            address: 'client@clientdomain.tld'
```

The new UI:

<img width="1570" height="1476" alt="Image" src="https://github.com/user-attachments/assets/4d71b29f-85e8-4a8f-8203-ba03fb06e61e" />
